### ISSUE TITLE
Detailed per-peer metrics should be optional 

### ISSUE THREAD

**Issue by ohrensessel** [freifunk-darmstadt/fastd-exporter#1]
Currently, the fastd-exporter provides several metrics on a per-peer basis, allowing e.g. to track the VPN usage of single peers. This might be undesirable when data minimization/avoidance is a key aspect.
Instead, it would be nice to just provide summaries (e.g. a metric for the number of connected peers) if requested to do so. Detailed per-peer metrics could be default, but disabling them via a parameter would be desirable.

**Comment by mweinelt** [comment]
Good idea, resolved in 39b21226c475fda72c2b9cf15015f43a4103f087

Peer metrics now need to be explicitly enabled with `--metrics.perpeer`.
